- name: Deploy to Kubernetes
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply deployment
      shell: |
        export KUBECONFIG={{ lookup('env','KUBECONFIG') }}
        kubectl apply -f ../deployment.yaml --validate=false
        kubectl apply -f ../service.yaml --validate=false